# Aegis Makefile

PY := uv run python
COMPOSE := docker compose

.PHONY: help sync test lint format up down logs migrate revision eval eval-gate fetch-models clean

help:
	@echo "Aegis - common commands"
	@echo ""
	@echo "  make sync          Install dependencies from uv.lock"
	@echo "  make test          Run the test suite"
	@echo "  make lint          Run ruff and mypy"
	@echo "  make format        Format the code with ruff"
	@echo ""
	@echo "  make up            Build and start local services"
	@echo "  make down          Stop local services"
	@echo "  make logs          Tail service logs"
	@echo "  make migrate       Apply database migrations"
	@echo "  make revision m=\"message\""
	@echo "                     Create an autogenerated migration"
	@echo ""
	@echo "  make eval          Run the detector evaluation on the golden set"
	@echo "  make eval-gate     Compare the latest eval report to the baseline"
	@echo "  make fetch-models  Pre-download ML model weights into ./models"
	@echo "  make clean         Remove local caches"

sync:
	uv sync

test:
	uv run pytest

lint:
	uv run ruff check .
	uv run ruff format --check .
	uv run mypy aegis

format:
	uv run ruff format .
	uv run ruff check --fix .

up:
	$(COMPOSE) up -d --build

down:
	$(COMPOSE) down

logs:
	$(COMPOSE) logs -f

migrate:
	uv run alembic upgrade head

revision:
	uv run alembic revision --autogenerate -m "$(m)"

eval:
	$(PY) -m aegis.eval run --golden data/golden --out reports/eval

eval-gate:
	$(PY) -m aegis.eval gate --baseline reports/eval/baseline.json

fetch-models:
	uv run --group analysis --group media python -m aegis.pipeline.fetch_models

clean:
	$(PY) -c "import pathlib, shutil; [shutil.rmtree(p, ignore_errors=True) for p in pathlib.Path('.').rglob('__pycache__')]; [shutil.rmtree(p, ignore_errors=True) for p in ['.pytest_cache', '.mypy_cache', '.ruff_cache', '.coverage', 'htmlcov']]"
