# Aegis Makefile

PY := uv run python
COMPOSE := docker compose

.PHONY: help sync test lint format up down logs migrate revision eval eval-gate eval-cache benchmark-models fetch-models frontend-install frontend-dev frontend-test frontend-build integration e2e clean

help:
	@echo "Aegis - common commands"
	@echo ""
	@echo "  make sync          Install dependencies from uv.lock"
	@echo "  make test          Run the test suite"
	@echo "  make lint          Run ruff and mypy"
	@echo "  make format        Format the code with ruff"
	@echo ""
	@echo "  make up            Build and start local services"
	@echo "  make down          Stop local services"
	@echo "  make logs          Tail service logs"
	@echo "  make migrate       Apply database migrations"
	@echo "  make revision m=\"message\""
	@echo "                     Create an autogenerated migration"
	@echo ""
	@echo "  make eval          Run the detector evaluation on the golden set"
	@echo "  make eval-gate     Compare the latest eval report to the baseline"
	@echo "  make eval-cache    Refresh the committed LLM and toxicity caches (needs Ollama)"
	@echo "  make benchmark-models"
	@echo "                     Compare local models on the labelled pilot set"
	@echo "  make fetch-models  Pre-download ML model weights into ./models"
	@echo ""
	@echo "  make frontend-install  Install dashboard dependencies"
	@echo "  make frontend-dev      Run the Vite dev server"
	@echo "  make frontend-test     Run the Vitest suite"
	@echo "  make frontend-build    Type-check and build the dashboard"
	@echo "  make integration   Durability tests (needs Docker, Postgres, RabbitMQ)"
	@echo "  make e2e           Seed and run the Playwright suite (API must be up)"
	@echo "  make clean         Remove local caches"

sync:
	uv sync

test:
	uv run pytest

lint:
	uv run ruff check .
	uv run ruff format --check .
	uv run mypy aegis

format:
	uv run ruff format .
	uv run ruff check --fix .

up:
	$(COMPOSE) up -d --build

down:
	$(COMPOSE) down

logs:
	$(COMPOSE) logs -f

migrate:
	uv run alembic upgrade head

revision:
	uv run alembic revision --autogenerate -m "$(m)"

eval:
	$(PY) -m aegis.eval run --golden data/golden --out reports/eval

eval-gate:
	$(PY) -m aegis.eval gate --baseline reports/eval/baseline.json

eval-cache:
	$(PY) -m aegis.eval cache --llm --toxicity --model aegis-intent

benchmark-models:
	$(PY) -m aegis.eval benchmark --models llama3.2:3b,qwen2.5:3b,gemma3:4b

fetch-models:
	uv run --group analysis --group media python -m aegis.pipeline.fetch_models

frontend-install:
	cd frontend && npm ci

frontend-dev:
	cd frontend && npm run dev

frontend-test:
	cd frontend && npm run test

frontend-build:
	cd frontend && npm run build

integration:
	AEGIS_INTEGRATION=1 uv run pytest tests/test_aegis_durability.py -v

e2e:
	uv run python frontend/e2e/seed.py
	cd frontend && npm run build
	cd frontend && npx playwright test

clean:
	$(PY) -c "import pathlib, shutil; [shutil.rmtree(p, ignore_errors=True) for p in pathlib.Path('.').rglob('__pycache__')]; [shutil.rmtree(p, ignore_errors=True) for p in ['.pytest_cache', '.mypy_cache', '.ruff_cache', '.coverage', 'htmlcov']]"
