# Aegis Makefile

PY := uv run python
COMPOSE := docker compose
AEGIS_DATA_REPO ?= https://github.com/Bucke200/Aegis-data.git

.PHONY: help sync test lint format up down logs migrate revision eval eval-smoke eval-gate eval-cache benchmark-models fetch-models data frontend-install frontend-dev frontend-test frontend-build integration e2e clean

help:
	@echo "Aegis - common commands"
	@echo ""
	@echo "  make sync          Install dependencies from uv.lock"
	@echo "  make test          Run the test suite"
	@echo "  make lint          Run ruff and mypy"
	@echo "  make format        Format the code with ruff"
	@echo ""
	@echo "  make up            Build and start local services"
	@echo "  make down          Stop local services"
	@echo "  make logs          Tail service logs"
	@echo "  make migrate       Apply database migrations"
	@echo "  make revision m=\"message\""
	@echo "                     Create an autogenerated migration"
	@echo ""
	@echo "  make eval          Run the detector evaluation on the private golden set"
	@echo "  make eval-smoke    Run the evaluation on the public smoke set"
	@echo "  make eval-gate     Compare the latest eval report to the baseline"
	@echo "  make eval-cache    Refresh the private LLM and toxicity caches (needs Ollama)"
	@echo "  make benchmark-models"
	@echo "                     Compare local models on the labelled pilot set"
	@echo "  make fetch-models  Pre-download ML model weights into ./models"
	@echo "  make data          Clone or update the private Aegis-data checkout"
	@echo ""
	@echo "  make frontend-install  Install dashboard dependencies"
	@echo "  make frontend-dev      Run the Vite dev server"
	@echo "  make frontend-test     Run the Vitest suite"
	@echo "  make frontend-build    Type-check and build the dashboard"
	@echo "  make integration   Durability tests (needs Docker, Postgres, RabbitMQ)"
	@echo "  make e2e           Seed and run the Playwright suite (API must be up)"
	@echo "  make clean         Remove local caches"

sync:
	uv sync

test:
	uv run pytest

lint:
	uv run ruff check .
	uv run ruff format --check .
	uv run mypy aegis

format:
	uv run ruff format .
	uv run ruff check --fix .

up:
	$(COMPOSE) up -d --build

down:
	$(COMPOSE) down

logs:
	$(COMPOSE) logs -f

migrate:
	uv run alembic upgrade head

revision:
	uv run alembic revision --autogenerate -m "$(m)"

data:
	@if [ -d data/private/.git ]; then \
		if git -C data/private remote get-url origin >/dev/null 2>&1; then \
			git -C data/private pull --ff-only; \
		else \
			echo "data/private is a local repo with no origin; add one with: git -C data/private remote add origin $(AEGIS_DATA_REPO)"; \
		fi; \
	elif [ -d data/private ]; then \
		echo "data/private exists but is not a git repo; move it aside first" && exit 1; \
	else \
		git clone $(AEGIS_DATA_REPO) data/private; \
	fi

eval:
	$(PY) -m aegis.eval run --golden data/private/golden --out data/private/reports/eval

eval-smoke:
	$(PY) -m aegis.eval run --golden data/smoke --out build/eval-smoke

eval-gate:
	$(PY) -m aegis.eval gate --baseline data/private/reports/eval/baseline.json --report data/private/reports/eval/report.json

eval-cache:
	$(PY) -m aegis.eval cache --golden data/private/golden --llm --toxicity --model aegis-intent \
		--out-llm data/private/caches/llm_cache.jsonl --out-toxicity data/private/caches/toxicity_cache.jsonl

benchmark-models:
	$(PY) -m aegis.eval benchmark --models llama3.2:3b,qwen2.5:3b,gemma3:4b \
		--golden data/private/golden --out data/private/reports/labelling

fetch-models:
	uv run --group analysis --group media python -m aegis.pipeline.fetch_models

frontend-install:
	cd frontend && npm ci

frontend-dev:
	cd frontend && npm run dev

frontend-test:
	cd frontend && npm run test

frontend-build:
	cd frontend && npm run build

integration:
	AEGIS_INTEGRATION=1 uv run pytest tests/test_aegis_durability.py -v

e2e:
	uv run python frontend/e2e/seed.py
	cd frontend && npm run build
	cd frontend && npx playwright test

clean:
	$(PY) -c "import pathlib, shutil; [shutil.rmtree(p, ignore_errors=True) for p in pathlib.Path('.').rglob('__pycache__')]; [shutil.rmtree(p, ignore_errors=True) for p in ['.pytest_cache', '.mypy_cache', '.ruff_cache', '.coverage', 'htmlcov']]"
